### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by mehranagh20** [reyllama/mixdl#1]
I get the following error while trying to train.

```
d: 1.3521; g: 8.8945; r1: 0.0002; path: 3.1181; mean path: 0.0173; augment: 0.0000:   0%|    | 1/150001 [00:50<2088:21:53, 50.12s/it]
Traceback (most recent call last):
  File "train_mixdl.py", line 781, in <module>
    train(args, loader, generator, discriminator, extra, g_optim, d_optim, e_optim, g_ema, device)
  File "train_mixdl.py", line 263, in train
    w = torch.matmul(alpha, w)
RuntimeError: mat1 dim 1 must match mat2 dim 0
```

Here is the training command I use:
```python3 train_mixdl.py 100-shot-obama/ --root ./result```

Could you please specify the list of hyperparameters needed for training?

**Comment by chaerinkong** [comment]
First of all, sorry for late reply. This code base is still on its refactoring process, which I hope to end soon :( In my opinion, your error could be fixed by using 

```
w = generator.get_latent(z)  # (Batch, 512)
fake_img, _ = generator([w], return_feats=False, input_is_latent=True)
w = torch.matmul(alpha, w)
interp_img, _ = generator([w], return_feats=False, input_is_latent=True)
```
instead of 
```
fake_img, w = generator([z], return_latents=True) 
w = torch.matmul(alpha, w)
interp_img, _ = generator(w, return_feats=False, input_is_latent=True)
```

I conjecture this is due to pytorch version mismatches, and I'll do my best to provide a more reliable code base.
